import { describe, it, expect, vi, beforeEach } from 'vitest';

// hoist the mock store AND the chain so they exist BEFORE vi.mock factory runs
const hoisted = vi.hoisted(() => {
  const captured: any[] = [];
  const deleteCaptured: any[] = [];

  const tableApi: any = {
    upsert: (rows: any) => { captured.push(rows); return Promise.resolve({ error: null }); },
    select: () => ({ ...tableApi, eq: () => ({ ...tableApi, maybeSingle: () => Promise.resolve({ data: null, error: null }), order: () => Promise.resolve({ data: [], error: null }) }), order: () => Promise.resolve({ data: [], error: null }), maybeSingle: () => Promise.resolve({ data: null, error: null }) }),
    eq: () => ({ ...tableApi, maybeSingle: () => Promise.resolve({ data: null, error: null }), order: () => Promise.resolve({ data: [], error: null }) }),
    maybeSingle: () => Promise.resolve({ data: null, error: null }),
    order: () => Promise.resolve({ data: [], error: null }),
    delete: (..._a: any[]) => {
      deleteCaptured.push(_a);
      const chainObj: any = {
        eq: () => chainObj,
        then: (resolve: any) => Promise.resolve({ error: null }).then(resolve),
      };
      return chainObj;
    },
  };

  const chain = {
    from: (_table: string) => tableApi,
  };
  return { captured, deleteCaptured, chain };
});

vi.mock('../../src/services/supabase/supabaseClient', () => ({
  supabase: hoisted.chain,
  isSupabaseConfigured: true,
}));

import { CloudSyncService } from '../../src/services/supabase/cloudSyncService';
import { FinovaState } from '../../src/services/storage/FinovaStorage';
import { DateUtils } from '../../src/domain/date/DateUtils';

const todayISO = DateUtils.getTodayISO();

function makeState(): FinovaState {
  return {
    accounts: [{
      id: 'acc-1', userId: 'user-1', name: 'BDO', bankPresetId: 'grbi', accountNumberMask: '••••',
      type: 'BANK', currency: 'PHP', initialBalance: 1000000, currentBalance: 1000000,
      icon: 'Building2', color: '#1C205E', includeInTotalBalance: true, isArchived: false,
      createdAt: todayISO, updatedAt: todayISO,
    }],
    transactions: [{
      id: 'tx-1', userId: 'user-1', accountId: 'acc-1', categoryId: 'cat-food', type: 'EXPENSE',
      amount: 50000, currency: 'PHP', merchant: 'Jollibee', note: '', date: todayISO, time: '12:00',
      tags: [], status: 'CONFIRMED', createdAt: todayISO, updatedAt: todayISO,
    }],
    categories: [],
    budgets: [{
      id: 'bud-1', userId: 'user-1', name: 'Food', amount: 500000, currency: 'PHP', period: 'MONTHLY',
      startDate: todayISO, endDate: todayISO, categoryIds: ['cat-food'], notifyThresholdPercentage: 80,
      isActive: true, rolloverUnused: false, createdAt: todayISO, updatedAt: todayISO,
    }],
    goals: [{
      id: 'goal-1', userId: 'user-1', name: 'Emergency', targetAmount: 1000000, currentAmount: 100000,
      currency: 'PHP', targetDate: todayISO, priority: 'ESSENTIAL', status: 'ON_TRACK', icon: 'Target',
      color: '#059669', isArchived: false, createdAt: todayISO, updatedAt: todayISO,
    }],
    commitments: [{
      id: 'comm-1', userId: 'user-1', title: 'Meralco', type: 'BILL', amount: 150000, currency: 'PHP',
      direction: 'OUTFLOW', status: 'PROJECTED', dueDate: todayISO, categoryId: 'cat-bills',
      accountId: 'acc-1', priority: 'ESSENTIAL', isAutoGenerated: false, createdAt: todayISO, updatedAt: todayISO,
    }],
    recurring: [{
      id: 'rec-1', userId: 'user-1', title: 'Netflix', amount: 39900, currency: 'PHP', type: 'EXPENSE',
      categoryId: 'cat-bills', accountId: 'acc-1', frequency: 'MONTHLY', startDate: todayISO,
      nextOccurrence: todayISO, endDate: undefined, isActive: true, reminderEnabled: true,
      createdAt: todayISO, updatedAt: todayISO,
    }],
    readNotificationIds: [],
    settings: {
      userId: 'user-1', userName: 'Test', currency: 'PHP', defaultTrackingPeriod: 'TODAY',
      budgetCycleMode: 'SEMI_MONTHLY_15_DAYS', semiMonthlyCutoffDay: 15, minimumReserve: 0,
      safeToSpendPeriod: 'END_OF_MONTH', darkTheme: false, notificationsEnabled: true,
      budgetWarningThreshold: 80, autoGenerateCommitmentsFromRecurring: true, hasCompletedOnboarding: true,
    },
  };
}

const fakeUser = { id: 'user-1', email: 't@x.com', fullName: 'Test', avatarUrl: null, isGuest: false };

describe('Cloud Sync — round-trip persistence of ALL plans data', () => {
  beforeEach(() => {
    hoisted.captured.length = 0;
    hoisted.deleteCaptured.length = 0;
  });

  it('syncStateToCloud writes budgets, goals, commitments, recurring (not just profiles/settings/accounts/tx)', async () => {
    const ok = await CloudSyncService.syncStateToCloud(makeState(), fakeUser as any);
    expect(ok).toBe(true);

    const payloads = hoisted.captured;
    const findArr = (pred: (row: any) => boolean) => payloads.find((p) => Array.isArray(p) && p[0] && pred(p[0]));

    const hasBudgets = !!findArr((r) => 'rollover_unused' in r);
    const hasGoals = !!findArr((r) => 'target_amount' in r);
    const hasCommitments = !!findArr((r) => 'due_date' in r);
    const hasRecurring = !!findArr((r) => 'next_occurrence' in r);
    const hasTx = !!findArr((r) => 'account_id' in r && 'category_id' in r);

    expect(hasTx).toBe(true);
    expect(hasBudgets).toBe(true);
    expect(hasGoals).toBe(true);
    expect(hasCommitments).toBe(true);
    expect(hasRecurring).toBe(true);
  });

  it('syncStateToCloud preserves transaction category_id (no destructive null)', async () => {
    await CloudSyncService.syncStateToCloud(makeState(), fakeUser as any);
    const txPayload = hoisted.captured
      .find((p) => Array.isArray(p) && p[0] && 'category_id' in p[0]) as any[];
    expect(txPayload).toBeTruthy();
    expect(txPayload[0].category_id).toBe('cat-food');
    expect(txPayload[0].category_id).not.toBeNull();
  });

  it('syncStateToCloud writes categories and preserves category_id in commitments and recurring', async () => {
    const s = makeState();
    s.categories = [{ id: 'cat-custom-1', userId: 'user-1', name: 'Custom Category', icon: 'Tag', color: '#ff0000', type: 'EXPENSE', isSystem: false, isArchived: false }];
    s.commitments[0].categoryId = 'cat-custom-1';
    s.recurring[0].categoryId = 'cat-custom-1';

    await CloudSyncService.syncStateToCloud(s, fakeUser as any);

    const catPayload = hoisted.captured.find((p) => Array.isArray(p) && p[0] && p[0].id === 'cat-custom-1') as any[];
    expect(catPayload).toBeTruthy();
    expect(catPayload[0].name).toBe('Custom Category');

    const commPayload = hoisted.captured.find((p) => Array.isArray(p) && p[0] && 'due_date' in p[0]) as any[];
    expect(commPayload[0].category_id).toBe('cat-custom-1');

    const recPayload = hoisted.captured.find((p) => Array.isArray(p) && p[0] && 'next_occurrence' in p[0]) as any[];
    expect(recPayload[0].category_id).toBe('cat-custom-1');
  });

  it('delete helper methods execute cleanly without exceptions', async () => {
    const delTx = await CloudSyncService.deleteTransactionFromCloud('tx-1', fakeUser as any);
    const delComm = await CloudSyncService.deleteCommitmentFromCloud('comm-1', fakeUser as any);
    const delRec = await CloudSyncService.deleteRecurringFromCloud('rec-1', fakeUser as any);
    const delBud = await CloudSyncService.deleteBudgetFromCloud('bud-1', fakeUser as any);
    const delGoal = await CloudSyncService.deleteGoalFromCloud('goal-1', fakeUser as any);

    expect(delTx).toBe(true);
    expect(delComm).toBe(true);
    expect(delRec).toBe(true);
    expect(delBud).toBe(true);
    expect(delGoal).toBe(true);
  });
});
