import { CommitmentDirection, MoneyCommitment, RecurringTransaction } from '../../types';
import { DateUtils } from '../date/DateUtils';
import { MoneyValue } from '../money/MoneyValue';

export class CommitmentEngine {
  /**
   * Generates projected money commitments from active recurring transactions for a specified date range.
   */
  public static generateCommitmentsFromRecurring(
    recurringTransactions: RecurringTransaction[],
    startDateISO: string,
    endDateISO: string
  ): MoneyCommitment[] {
    const commitments: MoneyCommitment[] = [];

    for (const rec of recurringTransactions) {
      if (!rec.isActive) continue;

      let occurrenceDate = rec.nextOccurrence || rec.startDate;
      const recEnd = rec.endDate || endDateISO;
      const finalHorizon = recEnd < endDateISO ? recEnd : endDateISO;

      // Fast-forward or generate occurrences up to horizon
      while (occurrenceDate <= finalHorizon) {
        if (occurrenceDate >= startDateISO) {
          const direction: CommitmentDirection = rec.type === 'INCOME' ? 'INFLOW' : 'OUTFLOW';
          const commitmentType = rec.type === 'INCOME' ? 'RECURRING_INCOME' : 'BILL';

          commitments.push({
            id: `comm-rec-${rec.id}-${occurrenceDate}`,
            userId: rec.userId,
            title: rec.title,
            type: commitmentType,
            amount: rec.amount,
            currency: rec.currency || 'PHP',
            direction,
            status: 'PROJECTED',
            dueDate: occurrenceDate,
            accountId: rec.accountId,
            categoryId: rec.categoryId,
            relatedRecurringTransactionId: rec.id,
            priority: 'ESSENTIAL',
            isAutoGenerated: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
          });
        }

        // Advance occurrence date based on frequency
        occurrenceDate = this.advanceOccurrenceDate(occurrenceDate, rec.frequency);
      }
    }

    return commitments;
  }

  /**
   * Advances a date string according to recurring frequency.
   */
  public static advanceOccurrenceDate(dateISO: string, frequency: string): string {
    switch (frequency) {
      case 'DAILY':
        return DateUtils.addDaysISO(dateISO, 1);
      case 'WEEKLY':
        return DateUtils.addDaysISO(dateISO, 7);
      case 'BIWEEKLY':
        return DateUtils.addDaysISO(dateISO, 14);
      case 'MONTHLY':
        return DateUtils.addMonthsISO(dateISO, 1);
      case 'YEARLY':
        return DateUtils.addMonthsISO(dateISO, 12);
      default:
        return DateUtils.addMonthsISO(dateISO, 1);
    }
  }

  /**
   * Identifies commitments that are past due as of reference date.
   */
  public static identifyOverdueCommitments(
    commitments: MoneyCommitment[],
    referenceDateISO?: string
  ): MoneyCommitment[] {
    const todayISO = referenceDateISO || DateUtils.getTodayISO();
    return commitments.filter(
      (c) => c.dueDate < todayISO && c.status !== 'COMPLETED' && c.status !== 'CANCELLED'
    );
  }

  /**
   * Sums essential upcoming outflow commitments for a given date window (e.g. rest of month).
   */
  public static calculateUpcomingEssentialOutflows(
    commitments: MoneyCommitment[],
    startDateISO: string,
    endDateISO: string
  ): MoneyValue {
    let totalMinor = 0;
    const currency = commitments[0]?.currency || 'PKR';

    for (const c of commitments) {
      if (c.direction !== 'OUTFLOW') continue;
      if (c.status === 'COMPLETED' || c.status === 'CANCELLED') continue;
      if (c.priority !== 'ESSENTIAL' && c.priority !== 'IMPORTANT') continue;
      if (DateUtils.isDateInRange(c.dueDate, startDateISO, endDateISO)) {
        totalMinor += c.amount;
      }
    }

    return MoneyValue.fromMinorUnits(totalMinor, currency);
  }
}
